sudo: required
dist: trusty    
language: python
python:
  - 2.7
  - 3.5
install:
  - sudo apt-get update
  - pip install tensorflow==1.0.1 numpy scipy nose pandas codecov coverage
  - python setup.py install
script:
  - nosetests --nologcapture --with-coverage --cover-package=GPflowOpt testing
after_success:
  - codecov
