sudo: required
dist: trusty    
language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - sudo apt-get update
  - pip install tensorflow==1.0.1
  - pip install --process-dependency-links .
  - pip install .[test]
  - pip install codecov
script:
  - nosetests --nologcapture --with-coverage --cover-package=GPflowOpt testing
after_success:
  - codecov
